---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{onboarding.name}}
  namespace: {{onboarding.namespace}}
  labels:
    app: {{onboarding.name}}
    repo: {{onboarding.repo}}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{onboarding.name}}
      repo: {{onboarding.repo}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: {{onboarding.name}}
        repo: {{onboarding.repo}}
      annotations:
        prometheus.io/port: '{{onboarding.containerPort}}'
        prometheus.io/scrape: 'true'
      {{#onboarding.istio.enable}}
        sidecar.istio.io/inject: "true"
      {{/onboarding.istio.enable}}
    spec:
      containers:
        - name: {{onboarding.name}}
          image: {{{onboarding.container}}}:{{onboarding.version}}
          ports:
            - containerPort: {{onboarding.containerPort}}
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: {{onboarding.containerPort}}
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: {{onboarding.containerPort}}
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 50m
              memory: 120Mi
            requests:
              cpu: 20m
              memory: 80Mi
