---
version: '3.6'

services:

  ntpl:
    image: ikerry/ntpl:v0.4.4
    working_dir: /app
    volumes:
      - ".:/app"
      - "$HOME/.kube:/root/.kube"

  ctpl:
    image: ikerry/ctpl:v0.1.4
    working_dir: /app
    volumes:
      - ".:/app"
      - "$HOME/.aws:/root/.aws"
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2

  kubectl:
    image: lachlanevenson/k8s-kubectl:v1.15.0
    working_dir: /app
    volumes:
      - ".:/app"
      - "$HOME/.kube:/root/.kube"

  pytest: &base
    build:
      context: .
    volumes:
      - ".:/app"
      - "$HOME/.aws:/root/.aws"
      - "$HOME/.kube:/root/.kube"
    entrypoint:
      - "make"
      - "test_in"

  sh:
    <<: *base
    entrypoint:
      - "sh"
