---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  KubeApplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: testRoleForKubeApp
      Path: /k8s/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
        - Effect: Allow
          Principal:
            AWS: "693429498512"
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: allow-to-operate-s3-resources
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:ListBucket
              - s3:ListAllMyBuckets
              - s3:PutObject
              - s3:GetObject
              - s3:GetBucketLocation
              - s3:DeleteObject
              - s3:ListObjects
              - s3:ListBucket
              Resource: "arn:aws:s3:::*"
